spring:
  web:
    cors:
      allowed-origins: "http://192.168.15.200:5173"
      allowed-methods: GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD
      max-age: 3600
      allowed-headers: "Access-Control-Allow-Origin"
      exposed-headers: "Access-Control-Allow-Origin"